# Generated by Django 3.1.2 on 2020-10-22 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_post_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(default='XXXXXXXXXX', max_length=10, validators=[django.core.validators.RegexValidator(message='Check your format of phone number. Up to 10 digits allowed.', regex='^\\d{10}$')]),
        ),
    ]
