# Generated by Django 3.1.2 on 2020-10-22 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20201022_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Check your format of phone number. Up to 10 digits allowed.', regex='^\\d{10}$')]),
        ),
    ]
