# Generated by Django 3.1.2 on 2020-10-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201022_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_image',
            field=models.ImageField(default='default.jpg', upload_to='book_pics'),
        ),
    ]
