# Generated by Django 3.1.2 on 2020-10-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_post_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book_image',
            field=models.ImageField(default='book.jpg', upload_to='book_pics'),
        ),
    ]
