# Generated by Django 3.1.2 on 2020-10-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0002_auto_20201029_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='book_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
